apiVersion: apps/v1
kind: Deployment
metadata:
  name: contestsubmission-backend
spec:
  template:
    spec:
      volumes:
        - name: jwt-keys
          secret:
            secretName: backend-jwt-keys
      containers:
        - name: contestsubmission-backend
          volumeMounts:
            - name: jwt-keys
              readOnly: true
              mountPath: "/secrets"
