---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: a8a2490367ba2e7a05830447000b10af1b52329b
    app.quarkus.io/vcs-uri: https://github.com/ContestSubmission/Backend
    app.quarkus.io/build-timestamp: 2023-12-17 - 17:11:44 +0000
  labels:
    app.kubernetes.io/name: contestsubmission-backend
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/managed-by: quarkus
  name: contestsubmission-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: contestsubmission-backend
    app.kubernetes.io/version: 0.0.1
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: contestsubmission-backend
    app.kubernetes.io/version: 0.0.1
  name: contestsubmission-backend-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: contestsubmission-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: contestsubmission-backend
    app.kubernetes.io/version: 0.0.1
  name: contestsubmission-backend-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: contestsubmission-backend
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: a8a2490367ba2e7a05830447000b10af1b52329b
    app.quarkus.io/vcs-uri: https://github.com/ContestSubmission/Backend
    app.quarkus.io/build-timestamp: 2023-12-17 - 17:11:44 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: contestsubmission-backend
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/managed-by: quarkus
  name: contestsubmission-backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: contestsubmission-backend
    app.kubernetes.io/version: 0.0.1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: a8a2490367ba2e7a05830447000b10af1b52329b
    app.quarkus.io/vcs-uri: https://github.com/ContestSubmission/Backend
    app.quarkus.io/build-timestamp: 2023-12-17 - 17:11:44 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: contestsubmission-backend
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/managed-by: quarkus
  name: contestsubmission-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.1
      app.kubernetes.io/name: contestsubmission-backend
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: a8a2490367ba2e7a05830447000b10af1b52329b
        app.quarkus.io/vcs-uri: https://github.com/ContestSubmission/Backend
        app.quarkus.io/build-timestamp: 2023-12-17 - 17:11:44 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 0.0.1
        app.kubernetes.io/name: contestsubmission-backend
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: backend-oidc-secret
            - configMapRef:
                name: postgres-config
          image: ghcr.io/contestsubmission/contestsubmission-backend:0.0.1-46
          imagePullPolicy: Always
          name: contestsubmission-backend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      serviceAccountName: contestsubmission-backend
