apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-contestsubmission-simulatan-me
  namespace: contestsubmission
spec:
  secretName: ssl-contestsubmission-simulatan-me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - "contestsubmission.simulatan.me"
    - "*.contestsubmission.simulatan.me"
    - "*.staging.contestsubmission.simulatan.me"
