apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`backend.staging.contestsubmission.simulatan.me`)
      services:
        - name: contestsubmission-backend
          port: 80
