apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contestsubmission-staging

resources:
- backend-jwt-keys.yml
- backend-s3-secret.yml
- backend-oidc-secret.yml
- backend-mail-secret.yml
- backend-config.yml
- ../../base
- https://raw.githubusercontent.com/ContestSubmission/KubernetesManifests/3.0.0-147/backend/kubernetes.yml
- backend-ingress.yml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: contestsubmission-backend
    spec:
      template:
        spec:
          volumes:
            - name: jwt-keys
              secret:
                secretName: backend-jwt-keys
          containers:
            - name: contestsubmission-backend
              volumeMounts:
                - name: jwt-keys
                  readOnly: true
                  mountPath: "/secrets"
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: backend-postgres-pvc
    spec:
      # 'standard' isn't available in k3s
      storageClassName: local-path
  target:
    kind: PersistentVolumeClaim
    name: backend-postgres-pvc
- patch: |-
    kind: Job
    apiVersion: batch/v1
    metadata:
      name: contestsubmission-backend-flyway-init
      # delete succeeded jobs before syncing
      # required because jobs are immutable
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
