apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casdoor-postgres-pvc
  namespace: contestsubmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: casdoor-postgres
  namespace: contestsubmission
  labels:
    app: casdoor-postgres
spec:
  selector:
    app: casdoor-postgres
  ports:
    - port: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: contestsubmission
  name: casdoor-postgres
  labels:
    app: casdoor-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor-postgres
  template:
    metadata:
      labels:
        app: casdoor-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: casdoor
            - name: POSTGRES_PASSWORD
              value: casdoor
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: casdoor-postgres-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: casdoor-postgres-pvc
          persistentVolumeClaim:
            claimName: casdoor-postgres-pvc
