apiVersion: v1
kind: Service
metadata:
  namespace: contestsubmission
  name: casdoor-svc
  labels:
    app: casdoor
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30100
  selector:
    app: casdoor
