apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  application.properties: |
    quarkus.http.cors=true
    quarkus.http.cors.origins=https://contestsubmission.simulatan.me,https://staging.contestsubmission.simulatan.me
    websiteUrl=https://contestsubmission.simulatan.me

