apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contestsubmission

resources:
- backend-jwt-keys.yml
- backend-s3-secret.yml
- ../../base
- backend-service.yml

patches:
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: backend-postgres-pvc
    spec:
      # 'standard' isn't available in k3s
      storageClassName: local-path
  target:
    kind: PersistentVolumeClaim
    name: backend-postgres-pvc
- patch: |-
    kind: Job
    apiVersion: batch/v1
    metadata:
      name: contestsubmission-backend-flyway-init
      # delete succeeded jobs before syncing
      # required because jobs are immutable
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

