apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contestsubmission

resources:
- backend-jwt-keys.yml
- backend-s3-secret.yml
- ../../base
- backend-service.yml

patches:
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: backend-postgres-pvc
    spec:
      # 'standard' isn't available in k3s
      storageClassName: local-path
  target:
    kind: PersistentVolumeClaim
    name: backend-postgres-pvc
- patch: |-
    kind: Job
    apiVersion: batch/v1
    metadata:
      name: contestsubmission-backend-flyway-init
      # delete succeeded jobs before syncing
      # required because jobs are immutable
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
- patch: |-
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: contestsubmission-backend
      annotations:
        # for some reason some field seems to be immutable? no clue which one tho
        # Deployment.apps "contestsubmission-backend" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"contestsubmission-backend", "app.kubernetes.io/version":""}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
        argocd.argoproj.io/sync-options: Replace=true
