apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contestsubmission

resources:
- backend-jwt-keys.yml
- backend-s3-secret.yml
- backend-oidc-secret.yml
- backend-mail-secret.yml
- backend-config.yml
- ../../base
- https://raw.githubusercontent.com/ContestSubmission/KubernetesManifests/4.2.0/backend/kubernetes.yml
- backend-service.yml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: contestsubmission-backend
    spec:
      template:
        spec:
          volumes:
            - name: jwt-keys
              secret:
                secretName: backend-jwt-keys
          containers:
            - name: contestsubmission-backend
              volumeMounts:
                - name: jwt-keys
                  readOnly: true
                  mountPath: "/secrets"
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: backend-postgres-pvc
    spec:
      # 'standard' isn't available in k3s
      storageClassName: local-path
  target:
    kind: PersistentVolumeClaim
    name: backend-postgres-pvc
