apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: casdoor
  namespace: argocd
spec:
  project: contestsubmission
  source:
    repoURL: 'https://github.com/ContestSubmission/GitOps'
    targetRevision: HEAD
    path: casdoor/overlays/prod
    kustomize:
      namespace: contestsubmission
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: contestsubmission
